name: Allure Report in GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Selenium tests with Mocha and Allure
        run: |
          npx mocha 'tests/**/*.js' --reporter allure-mocha --parallel --jobs 4 --reporter-options allureResults=allure-results
        env:
          CI: true
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: allure-history
        continue-on-error: true

      - name: Generate Allure report
        if: always()  
        run: npm run allure:generate -- --clean

      - name: Allure Report action from marketplace
        if: always()  
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to GitHub Pages
        if: always() 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_branch: gh-pages
          publish_dir: allure-report